// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking "parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *Observer) Update(_a0 *parking.Lot, _a1 bool) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewObserver interface {
	mock.TestingT
	Cleanup(func())
}

// NewObserver creates a new instance of Observer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewObserver(t mockConstructorTestingTNewObserver) *Observer {
	mock := &Observer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
